language: java
jdk: openjdk11

# https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - unset _JAVA_OPTIONS
  
matrix:
  include:
  - env: FOLDER="LabOne" PRO_SPECIAL_BUILD='early-access'
  - env: FOLDER="LabTwo" PRO_SPECIAL_BUILD='early-access'
  - env: FOLDER="LabThree" PRO_SPECIAL_BUILD='early-access'
  - env: FOLDER="LabFour" PRO_SPECIAL_BUILD='early-access-loom'
  - env: FOLDER="consise-method" PRO_SPECIAL_BUILD="early-access-amber'
  - env: FOLDER="LabFive" PRO_SPECIAL_BUILD='early-access'
  - env: FOLDER="LabSix" PRO_SPECIAL_BUILD='early-access'

install:
  - cd $FOLDER
  - java pro_wrapper.java version

script:
  - ./pro/bin/pro version
  - ./pro/bin/pro 
